import { create } from 'zustand'
import { kanji } from '../types/words'

export interface kanjiStore {
  kanji: kanji[]
}

export const useKanjiStore = create<kanjiStore>((set, get) => ({
  kanji: [
    { kanji: 'あなた', hiragana: 'あなた', meaning: "you (usually when one doesn't know the person)" },
    { kanji: 'さん', hiragana: 'さん', meaning: 'san (neutral polite honorific)' },
    { kanji: '彼', hiragana: 'かれ', meaning: 'he, him' },
    { kanji: '好き', hiragana: 'すき', meaning: 'like, fond of' },
    { kanji: '人', hiragana: 'ひと', meaning: 'person' },
    { kanji: 'いい', hiragana: 'いい', meaning: 'good' },
    { kanji: '日本語', hiragana: 'にほんご', meaning: 'Japanese language' },
    { kanji: '勉強', hiragana: 'べんきょう', meaning: 'study' },
    { kanji: 'どれ', hiragana: 'どれ', meaning: 'which, what' },
    { kanji: '毎日', hiragana: 'まいにち', meaning: 'every day' },
    { kanji: '兄', hiragana: 'あに', meaning: 'older brother' },
    { kanji: 'いる', hiragana: 'いる', meaning: 'have, exist (animate)' },
    { kanji: 'ある', hiragana: 'ある', meaning: 'have, exist (inanimate)' },
    { kanji: 'あまり', hiragana: 'あまり', meaning: '(not) very, (not) much' },
    { kanji: '今', hiragana: 'いま', meaning: 'now' },
    { kanji: '時間', hiragana: 'じかん', meaning: 'time, hour' },
    { kanji: '無い', hiragana: 'ない', meaning: 'to not be' },
    { kanji: '見る', hiragana: 'みる', meaning: 'see, look at' },
    { kanji: '全然', hiragana: 'ぜんぜん', meaning: '(not) at all' },
    { kanji: '面白い', hiragana: 'おもしろい', meaning: 'interesting, amusing' },
    { kanji: 'する', hiragana: 'する', meaning: 'do, make' },
    { kanji: 'なる', hiragana: 'なる', meaning: 'become, result in, come (to do)' },
    { kanji: '先生', hiragana: 'せんせい', meaning: 'teacher' },
    { kanji: 'ください', hiragana: 'ください', meaning: 'please give..., please do...' },
    { kanji: '名前', hiragana: 'なまえ', meaning: 'name' },
    { kanji: '教える', hiragana: 'おしえる', meaning: 'teach, tell' },
    { kanji: '置く', hiragana: 'おく', meaning: 'put, place' },
    { kanji: '家', hiragana: 'いえ', meaning: 'house, home' },
    { kanji: '帰る', hiragana: 'かえる', meaning: 'return, go back' },
    { kanji: '話', hiragana: 'はなし', meaning: 'talk, story' },
    { kanji: '知る', hiragana: 'しる', meaning: 'know' },
    { kanji: '彼女', hiragana: 'かのじょ', meaning: 'she, her, girlfriend' },
    { kanji: 'ちゃん', hiragana: 'ちゃん', meaning: 'chan (affectionate honorific)' },
    { kanji: 'はい', hiragana: 'はい', meaning: 'yes (polite)' },
    { kanji: 'いいえ', hiragana: 'いいえ', meaning: 'no (polite)' },
    { kanji: '日本', hiragana: 'にほん', meaning: 'Japan' },
    { kanji: '学校', hiragana: 'がっこう', meaning: 'school' },
    { kanji: '行く', hiragana: 'いく', meaning: 'go' },
    { kanji: '明日', hiragana: 'あした', meaning: 'tomorrow' },
    { kanji: '来る', hiragana: 'くる', meaning: 'come' },
    { kanji: 'また', hiragana: 'また', meaning: 'again, also' },
    { kanji: 'いつ', hiragana: 'いつ', meaning: 'when' },
    { kanji: '思う', hiragana: 'おもう', meaning: 'think' },
    { kanji: '会う', hiragana: 'あう', meaning: 'meet' },
    { kanji: '方', hiragana: 'ほう', meaning: 'direction, side, person' },
    { kanji: '聞く', hiragana: 'きく', meaning: 'hear, ask' },
    { kanji: '分かる', hiragana: 'わかる', meaning: 'understand' },
    { kanji: 'もっと', hiragana: 'もっと', meaning: 'more, a bit more' },
    { kanji: 'ゆっくり', hiragana: 'ゆっくり', meaning: 'slowly' },
    { kanji: '言う', hiragana: 'いう', meaning: 'say' },
    { kanji: '友達', hiragana: 'ともだち', meaning: 'friend, companion' },
    { kanji: '待つ', hiragana: 'まつ', meaning: 'wait' },
    { kanji: '町', hiragana: 'まち', meaning: 'town, city' },
    { kanji: '高い', hiragana: 'たかい', meaning: 'expensive, high, tall' },
    { kanji: '父', hiragana: 'ちち', meaning: "(speaker's) father" },
    { kanji: '大好き', hiragana: 'だいすき', meaning: 'love' },
    { kanji: '母', hiragana: 'はは', meaning: "(speaker's) mother" },
    { kanji: 'おじいさん', hiragana: 'おじいさん', meaning: 'grandfather' },
    { kanji: 'おばあさん', hiragana: 'おばあさん', meaning: 'grandmother' },
    { kanji: '元気', hiragana: 'げんき', meaning: 'energetic, healthy' },
    { kanji: 'いつも', hiragana: 'いつも', meaning: 'always, usually' },
    { kanji: '持つ', hiragana: 'もつ', meaning: 'have, hold' },
    { kanji: '使う', hiragana: 'つかう', meaning: 'use' },
    { kanji: '始める', hiragana: 'はじめる', meaning: 'start' },
    { kanji: '今日', hiragana: 'きょう', meaning: 'today' },
    { kanji: '食べる', hiragana: 'たべる', meaning: 'eat' },
    { kanji: 'くれる', hiragana: 'くれる', meaning: "give (receiver is in the speaker's group)" },
    { kanji: 'もらう', hiragana: 'もらう', meaning: 'receive' },
    { kanji: '物', hiragana: 'もの', meaning: 'thing, object' },
    { kanji: '君', hiragana: 'きみ', meaning: 'you (to someone of equal or lower status)' },
    { kanji: '中', hiragana: 'なか', meaning: 'inside, middle' },
    { kanji: '出来る', hiragana: 'できる', meaning: 'can do, be good at' },
    { kanji: '本当', hiragana: 'ほんとう', meaning: 'truth, reality' },
    { kanji: '立つ', hiragana: 'たつ', meaning: 'stand, rise' },
    { kanji: '前', hiragana: 'まえ', meaning: 'front, before' },
    { kanji: '入る', hiragana: 'はいる', meaning: 'enter' },
    { kanji: '家族', hiragana: 'かぞく', meaning: 'family' },
    { kanji: '住む', hiragana: 'すむ', meaning: 'live, reside' },
    { kanji: '大きな', hiragana: 'おおきな', meaning: 'big, large' },
    { kanji: '声', hiragana: 'こえ', meaning: 'voice, sound' },
    { kanji: '目', hiragana: 'め', meaning: 'eye' },
    { kanji: '手', hiragana: 'て', meaning: 'hand' },
    { kanji: '上げる', hiragana: 'あげる', meaning: 'raise, increase' },
    { kanji: '嫌い', hiragana: 'きらい', meaning: 'dislike' },
    { kanji: 'おじいさん', hiragana: 'おじいさん', meaning: 'grandfather' },
    { kanji: 'おばあさん', hiragana: 'おばあさん', meaning: 'grandmother' },
    { kanji: '元気', hiragana: 'げんき', meaning: 'energetic, healthy' },
    { kanji: 'いつも', hiragana: 'いつも', meaning: 'always, usually' },
    { kanji: '持つ', hiragana: 'もつ', meaning: 'have, hold' },
    { kanji: 'みんな', hiragana: 'みんな', meaning: 'all, everybody' },
    { kanji: '使う', hiragana: 'つかう', meaning: 'use' },
    { kanji: '大丈夫', hiragana: 'だいじょうぶ', meaning: 'alright, OK' },
    { kanji: '始める', hiragana: 'はじめる', meaning: 'start' },
    { kanji: '今日', hiragana: 'きょう', meaning: 'today' },
    { kanji: '部屋', hiragana: 'へや', meaning: 'room' },
    { kanji: '悪い', hiragana: 'わるい', meaning: 'bad' },
    { kanji: 'まあ', hiragana: 'まあ', meaning: 'well...' },
    { kanji: '食べる', hiragana: 'たべる', meaning: 'eat' },
    { kanji: '場所', hiragana: 'ばしょ', meaning: 'place, location' },
    { kanji: '呼ぶ', hiragana: 'よぶ', meaning: 'call, name' },
    { kanji: '動く', hiragana: 'うごく', meaning: 'move' },
    { kanji: '気持ち', hiragana: 'きもち', meaning: 'feeling, sensation' },
    { kanji: '誰', hiragana: 'だれ', meaning: 'who' },
    { kanji: '子', hiragana: 'こ', meaning: 'child, kid' },
    { kanji: 'どんな', hiragana: 'どんな', meaning: 'what kind of...' },
    { kanji: '意味', hiragana: 'いみ', meaning: 'meaning, significance' },
    { kanji: '言葉', hiragana: 'ことば', meaning: 'word, language' },
    { kanji: '心配', hiragana: 'しんぱい', meaning: 'worry' },
    { kanji: '様子', hiragana: 'ようす', meaning: 'appearance, state' },
    { kanji: '信じる', hiragana: 'しんじる', meaning: 'to believe, to trust' },
    { kanji: '自分', hiragana: 'じぶん', meaning: 'self, oneself' },
    { kanji: '調べる', hiragana: 'しらべる', meaning: 'look up, search' },
    { kanji: '事', hiragana: 'こと', meaning: 'thing, incident' },
    { kanji: '同じ', hiragana: 'おなじ', meaning: 'same, identical' },
    { kanji: '申し訳ない', hiragana: 'もうしわけない', meaning: 'sorry, inexcusable' },
    { kanji: 'もちろん', hiragana: 'もちろん', meaning: 'of course, no doubt' },
    { kanji: 'とても', hiragana: 'とても', meaning: 'very' },
    { kanji: '楽しい', hiragana: 'たのしい', meaning: 'fun, enjoyable' },
    { kanji: '失礼します', hiragana: 'しつれいします', meaning: 'pardon me, excuse me (e.g., when leaving)' }
  ]
}))
